// ═══════════════════════════════════════════════
// TRADUCTIONS — Cœur de Ville
// ═══════════════════════════════════════════════

const TRANSLATIONS = {

  fr: {
    hero_title: "L'âme de la ville,",
    hero_sub: "révélée.",
    explorer: "Explorer maintenant",
    nav_home: "Accueil", nav_map: "Carte", nav_shops: "Commerces", nav_agenda: "Agenda",
    pill_patrimoine: "Patrimoine", pill_gastro: "Gastronomie", pill_artisanat: "Artisanat", pill_agenda: "Agenda",
    section_patrimoine: "Sites patrimoniaux", section_patrimoine_sub: "Les incontournables de la ville",
    section_insolites: "Lieux & anecdotes", section_insolites_sub: "Secrets et légendes",
    section_commerces: "Commerces locaux", section_commerces_sub: "Artisans & saveurs",
    section_agenda: "Agenda & Animations", section_agenda_sub: "À ne pas manquer",
    voir_tout: "Voir tout", voir_carte: "Voir sur la carte", voir_fiche: "Lire la fiche",
    changer_ville: "Changer de ville",
    concierge_title: "Besoin d'un guide ?",
    concierge_sub: "Notre concierge numérique vous propose un itinéraire personnalisé selon votre temps et vos envies.",
    concierge_btn: "Démarrer le parcours",
    cat_monument: "Monument", cat_religieux: "Religieux", cat_militaire: "Militaire",
    cat_culturel: "Culturel", cat_nature: "Nature", cat_restaurant: "Restaurant",
    cat_artisan: "Artisan", cat_commerce: "Commerce", cat_evenement: "Événement", cat_insolite: "Insolite",
    place_fort: "Fort Saint-André",
    place_chartreuse: "Chartreuse du Val de Bénédiction",
    place_tour: "Tour Philippe le Bel",
    place_musee: "Musée Pierre de Luxembourg",
    place_colline: "Colline des Mourgues",
    place_partition: "La Partition Gravée du Cardinal",
    place_lezard: "La Légende des Lézards",
    place_bronzini: "Maison Bronzini",
    place_table: "La Table du Fort",
    place_santons: "Santons Bérard",
    place_marche_j: "Marché du Jeudi",
    place_marche_s: "Marché du Samedi",
    place_foodtrucks: "Food Trucks Villeneuve",
    place_saintjean: "Fête de la Saint-Jean",
    place_estivales: "Estivales de la Chartreuse",
    place_noel: "Marché de Noël Médiéval",
    desc_fort: "Forteresse royale du XIVe siècle érigée par Jean le Bon. Ses deux tours jumelles dominent le Rhône et offrent une vue imprenable sur Avignon.",
    desc_chartreuse: "La plus grande chartreuse de France, fondée en 1356 par le pape Innocent VI. Lieu de sérénité et de création artistique.",
    desc_tour: "Sentinelle médiévale à l'entrée du pont Saint-Bénézet, offrant un panorama unique sur Avignon et le Rhône.",
    desc_musee: "Installé dans l'ancien palais du cardinal Arnaud de Via, le musée abrite le Couronnement de la Vierge d'Enguerrand Quarton.",
    desc_colline: "Promontoire secret offrant la plus belle vue sur le Palais des Papes, le Mont-Ventoux et les Alpilles.",
    desc_partition: "En rénovant un palais cardinalice, la mairie découvre gravée dans le marbre une partition du XIVe siècle — unique au monde.",
    desc_lezard: "Ils ouvrirent la malle d'or et des milliers de lézards s'échappèrent. La légende qui a donné son surnom aux Villeneuvois.",
    desc_bronzini: "Cuisine provençale sous les remparts — agneau des Alpilles, truffes du Vaucluse, vins des Côtes du Rhône.",
    desc_santons: "Atelier familial de santons provençaux modelés et peints à la main depuis 3 générations.",
    desc_marche_j: "Maraîchers, fromagers, oliviers et fleurs — chaque jeudi matin place Charles David.",
    desc_marche_s: "Producteurs locaux en circuits courts — vins AOC, miels, pains artisanaux.",
    desc_foodtrucks: "Cuisine du monde en plein air — convivialité, saveurs et soirées animées.",
    desc_saintjean: "Feux de joie et torches sur les remparts du Fort Saint-André au solstice d'été.",
    desc_estivales: "Résidences d'artistes et concerts dans l'écrin de la Chartreuse.",
    desc_noel: "Artisans en costume, vin chaud et animations historiques en décembre.",
    // Périodes historiques
    era_xive: "XIVe siècle",
    era_xiiie: "XIIIe siècle",
    era_romaine: "Époque romaine",
    era_ier: "Ier siècle",
    // Nouvelles sections
    sec_visites: "Idées de visites",
    sec_visites_sub: "Selon vos envies",
    visite_famille: "En famille",
    visite_couple: "En couple",
    visite_amis: "Entre amis",
    visite_solo: "En solo",
    sec_cdc: "Coup de cœur",
    sec_cdc_sub: "La sélection de la semaine",
    cdc_badge: "Coup de cœur",
    cdc_label: "À ne pas manquer cette semaine",
    cdc_desc: "Le plus grand monastère de France vous ouvre ses cloîtres. Un lieu hors du temps.",
    sec_aujourdhui: "Aujourd'hui à Villeneuve",
    sec_aujourdhui_sub: "Ce qui se passe maintenant",
  },

  en: {
    hero_title: "The soul of the city,",
    hero_sub: "revealed.",
    explorer: "Explore now",
    nav_home: "Home", nav_map: "Map", nav_shops: "Shops", nav_agenda: "Events",
    pill_patrimoine: "Heritage", pill_gastro: "Gastronomy", pill_artisanat: "Crafts", pill_agenda: "Events",
    section_patrimoine: "Heritage sites", section_patrimoine_sub: "Must-see landmarks",
    section_insolites: "Stories & legends", section_insolites_sub: "Secrets of the city",
    section_commerces: "Local businesses", section_commerces_sub: "Artisans & flavours",
    section_agenda: "Events & Activities", section_agenda_sub: "Not to be missed",
    voir_tout: "See all", voir_carte: "View on map", voir_fiche: "Read more",
    changer_ville: "Change city",
    concierge_title: "Need a guide?",
    concierge_sub: "Our digital concierge suggests a personalised itinerary based on your time and preferences.",
    concierge_btn: "Start the tour",
    cat_monument: "Monument", cat_religieux: "Religious", cat_militaire: "Military",
    cat_culturel: "Cultural", cat_nature: "Nature", cat_restaurant: "Restaurant",
    cat_artisan: "Artisan", cat_commerce: "Shop", cat_evenement: "Event", cat_insolite: "Unusual",
    place_fort: "Fort Saint-André",
    place_chartreuse: "Chartreuse du Val de Bénédiction",
    place_tour: "Tour Philippe le Bel",
    place_musee: "Pierre de Luxembourg Museum",
    place_colline: "Colline des Mourgues",
    place_partition: "The Cardinal's Engraved Score",
    place_lezard: "The Legend of the Lizards",
    place_bronzini: "Maison Bronzini",
    place_table: "La Table du Fort",
    place_santons: "Santons Bérard",
    place_marche_j: "Thursday Market",
    place_marche_s: "Saturday Market",
    place_foodtrucks: "Villeneuve Food Trucks",
    place_saintjean: "Saint-Jean Festival",
    place_estivales: "Chartreuse Summer Festival",
    place_noel: "Medieval Christmas Market",
    desc_fort: "A 14th-century royal fortress built by King John II. Its twin towers overlook the Rhone and offer a breathtaking view of Avignon.",
    desc_chartreuse: "The largest charterhouse in France, founded in 1356 by Pope Innocent VI. A place of serenity and artistic creation.",
    desc_tour: "A medieval sentinel at the entrance of the Pont Saint-Benezet, offering a unique panorama over Avignon and the Rhone.",
    desc_musee: "Housed in the former palace of Cardinal Arnaud de Via, the museum holds Enguerrand Quarton's Coronation of the Virgin.",
    desc_colline: "A secret hilltop with the finest view over the Palace of the Popes, Mont Ventoux and the Alpilles.",
    desc_partition: "While renovating a cardinal's palace, the town discovered a 14th-century score engraved in marble — unique in the world.",
    desc_lezard: "They opened the golden chest and thousands of lizards escaped. The legend that gave the people of Villeneuve their nickname.",
    desc_bronzini: "Provencal cuisine beneath the ramparts — Alpilles lamb, Vaucluse truffles, Cotes du Rhone wines.",
    desc_santons: "A family workshop crafting hand-painted Provencal figurines for 3 generations.",
    desc_marche_j: "Growers, cheesemakers, olive oil and flowers — every Thursday morning on Place Charles David.",
    desc_marche_s: "Local producers, short supply chains — AOC wines, honeys, artisan breads.",
    desc_foodtrucks: "World cuisine outdoors — conviviality, flavours and lively evenings.",
    desc_saintjean: "Bonfires and torches on the ramparts of Fort Saint-Andre at midsummer.",
    desc_estivales: "Artist residencies and concerts in the stunning setting of the Chartreuse.",
    desc_noel: "Costumed artisans, mulled wine and historical events in December.",
    // Historical periods
    era_xive: "14th century",
    era_xiiie: "13th century",
    era_romaine: "Roman era",
    era_ier: "1st century",
    // New sections
    sec_visites: "Visit ideas",
    sec_visites_sub: "Choose your experience",
    visite_famille: "With family",
    visite_couple: "As a couple",
    visite_amis: "With friends",
    visite_solo: "Solo",
    sec_cdc: "Editor's pick",
    sec_cdc_sub: "This week's selection",
    cdc_badge: "Editor's pick",
    cdc_label: "Not to be missed this week",
    cdc_desc: "France's largest charterhouse opens its cloisters to you. A timeless place.",
    sec_aujourdhui: "Today in Villeneuve",
    sec_aujourdhui_sub: "What's happening now",
  },

  es: {
    hero_title: "El alma de la ciudad,",
    hero_sub: "revelada.",
    explorer: "Explorar ahora",
    nav_home: "Inicio", nav_map: "Mapa", nav_shops: "Comercios", nav_agenda: "Agenda",
    pill_patrimoine: "Patrimonio", pill_gastro: "Gastronomia", pill_artisanat: "Artesania", pill_agenda: "Agenda",
    section_patrimoine: "Patrimonio", section_patrimoine_sub: "Los imprescindibles",
    section_insolites: "Lugares y leyendas", section_insolites_sub: "Secretos de la ciudad",
    section_commerces: "Comercios locales", section_commerces_sub: "Artesanos y sabores",
    section_agenda: "Agenda y Actividades", section_agenda_sub: "No te lo pierdas",
    voir_tout: "Ver todo", voir_carte: "Ver en el mapa", voir_fiche: "Leer mas",
    changer_ville: "Cambiar ciudad",
    concierge_title: "Necesitas un guia?",
    concierge_sub: "Nuestro concierge digital te propone un itinerario personalizado segun tu tiempo y tus gustos.",
    concierge_btn: "Iniciar el recorrido",
    cat_monument: "Monumento", cat_religieux: "Religioso", cat_militaire: "Militar",
    cat_culturel: "Cultural", cat_nature: "Naturaleza", cat_restaurant: "Restaurante",
    cat_artisan: "Artesano", cat_commerce: "Comercio", cat_evenement: "Evento", cat_insolite: "Insolito",
    place_fort: "Fuerte Saint-Andre",
    place_chartreuse: "Cartuja del Val de Bendicion",
    place_tour: "Torre Philippe le Bel",
    place_musee: "Museo Pierre de Luxembourg",
    place_colline: "Colina des Mourgues",
    place_partition: "La Partitura Grabada del Cardenal",
    place_lezard: "La Leyenda de los Lagartos",
    place_bronzini: "Maison Bronzini",
    place_table: "La Table du Fort",
    place_santons: "Santons Berard",
    place_marche_j: "Mercado del Jueves",
    place_marche_s: "Mercado del Sabado",
    place_foodtrucks: "Food Trucks Villeneuve",
    place_saintjean: "Fiesta de San Juan",
    place_estivales: "Festival de Verano de la Cartuja",
    place_noel: "Mercado Medieval de Navidad",
    desc_fort: "Fortaleza real del siglo XIV construida por Juan II. Sus dos torres gemelas dominan el Rodano y ofrecen una vista impresionante de Avignon.",
    desc_chartreuse: "La cartuja mas grande de Francia, fundada en 1356 por el papa Inocencio VI. Un lugar de serenidad y creacion artistica.",
    desc_tour: "Centinela medieval a la entrada del Pont Saint-Benezet, con un panorama unico sobre Avignon y el Rodano.",
    desc_musee: "Instalado en el antiguo palacio del cardenal Arnaud de Via, el museo alberga la Coronacion de la Virgen de Enguerrand Quarton.",
    desc_colline: "Promontorio secreto con la mejor vista sobre el Palacio de los Papas, el Mont Ventoux y los Alpilles.",
    desc_partition: "Al renovar un palacio cardenalicio, el ayuntamiento descubrio grabada en marmol una partitura del siglo XIV — unica en el mundo.",
    desc_lezard: "Abrieron el cofre de oro y miles de lagartos escaparon. La leyenda que dio su apodo a los habitantes de Villeneuve.",
    desc_bronzini: "Cocina provenzal bajo las murallas — cordero de los Alpilles, trufas del Vaucluse, vinos de los Cotes du Rhone.",
    desc_santons: "Taller familiar de figuras provenzales modeladas y pintadas a mano desde hace 3 generaciones.",
    desc_marche_j: "Agricultores, queseros, aceitunas y flores — cada jueves por la manana en la plaza Charles David.",
    desc_marche_s: "Productores locales de proximidad — vinos AOC, mieles, panes artesanales.",
    desc_foodtrucks: "Cocina del mundo al aire libre — convivencia, sabores y veladas animadas.",
    desc_saintjean: "Hogueras y antorchas en las murallas del Fuerte Saint-Andre en el solsticio de verano.",
    desc_estivales: "Residencias de artistas y conciertos en el marco de la Cartuja.",
    desc_noel: "Artesanos en traje, vino caliente y animaciones historicas en diciembre.",
    // Períodos históricos
    era_xive: "Siglo XIV",
    era_xiiie: "Siglo XIII",
    era_romaine: "Época romana",
    era_ier: "Siglo I",
    // Nuevas secciones
    sec_visites: "Ideas de visitas",
    sec_visites_sub: "Elige tu experiencia",
    visite_famille: "En familia",
    visite_couple: "En pareja",
    visite_amis: "Con amigos",
    visite_solo: "Solo",
    sec_cdc: "Seleccion editorial",
    sec_cdc_sub: "La seleccion de la semana",
    cdc_badge: "Seleccion editorial",
    cdc_label: "No te lo pierdas esta semana",
    cdc_desc: "La cartuja mas grande de Francia te abre sus claustros. Un lugar fuera del tiempo.",
    sec_aujourdhui: "Hoy en Villeneuve",
    sec_aujourdhui_sub: "Lo que pasa ahora",
  }
};

function getLang() {
  try { return localStorage.getItem('cdv_lang') || 'fr'; } catch(e) { return 'fr'; }
}

function T(key) {
  var lang = getLang();
  return (TRANSLATIONS[lang] && TRANSLATIONS[lang][key]) || TRANSLATIONS.fr[key] || key;
}
