// ═══════════════════════════════════════════════════
// DATA/POIS.JS — Lieux, commerces, événements de la ville
// Seul fichier à modifier pour chaque nouvelle ville
// ═══════════════════════════════════════════════════

// ═══════════════════════════════════════════════════════════
// DATA/POIS.JS — SAINT-RÉMY-DE-PROVENCE
// Ajouter / modifier les lieux ici uniquement
// ═══════════════════════════════════════════════════════════

// ─── CATÉGORIES ─────────────────────────────────────────────
const CATS = {
  monument:  { label:'Monument',  color:'#c0392b', dot:'#e74c3c' },
  religieux: { label:'Religieux', color:'#8b5e3c', dot:'#a0714f' },
  militaire: { label:'Militaire', color:'#2c3e50', dot:'#4a6274' },
  culturel:  { label:'Culturel',  color:'#6b3fa0', dot:'#8e5cb5' },
  naturel:   { label:'Nature',    color:'#27ae60', dot:'#2ecc71' },
  restaurant:{ label:'Restaurant',color:'#e67e22', dot:'#f39c12' },
  artisan:   { label:'Artisan',   color:'#16a085', dot:'#1abc9c' },
  commerce:  { label:'Commerce',  color:'#8e44ad', dot:'#9b59b6' },
  fete:      { label:'Événement', color:'#2980b9', dot:'#3498db' },
  evenement: { label:'Événement', color:'#dc5028', dot:'#dc5028' },
};

// ─── THÈMES VISUELS PAR CATÉGORIE ───────────────────────────
const CAT_THEMES = {
  militaire: {
    tint: 'rgba(40,10,10,0.45)',
    particles: 'rgba(200,60,40,0.55)',
    accent: '#c0392b', accentLight: '#e74c3c',
    badgeBg: 'rgba(80,10,10,0.7)', badgeColor: '#e88',
    btnGrad: 'linear-gradient(135deg,#4a0a0a,#8b1a1a)',
    statColor: '#e74c3c',
  },
  religieux: {
    tint: 'rgba(60,30,0,0.38)',
    particles: 'rgba(255,210,80,0.7)',
    accent: '#c9a227', accentLight: '#f6be39',
    badgeBg: 'rgba(50,30,0,0.7)', badgeColor: '#f6d76b',
    btnGrad: 'linear-gradient(135deg,#4a3000,#9a6800)',
    statColor: '#f6be39',
  },
  monument: {
    tint: 'rgba(30,20,10,0.4)',
    particles: 'rgba(200,160,80,0.6)',
    accent: '#a0784a', accentLight: '#c9964e',
    badgeBg: 'rgba(40,25,10,0.7)', badgeColor: '#d4a96a',
    btnGrad: 'linear-gradient(135deg,#3d2200,#8b5e00)',
    statColor: '#c9964e',
  },
  culturel: {
    tint: 'rgba(40,15,60,0.38)',
    particles: 'rgba(180,120,240,0.55)',
    accent: '#7b3fa0', accentLight: '#a855f7',
    badgeBg: 'rgba(30,10,50,0.7)', badgeColor: '#c084fc',
    btnGrad: 'linear-gradient(135deg,#2a0a40,#6b2fa0)',
    statColor: '#a855f7',
  },
  naturel: {
    tint: 'rgba(10,30,15,0.38)',
    particles: 'rgba(80,200,120,0.5)',
    accent: '#1a6b35', accentLight: '#22c55e',
    badgeBg: 'rgba(5,25,10,0.7)', badgeColor: '#4ade80',
    btnGrad: 'linear-gradient(135deg,#0a2e18,#1a6b35)',
    statColor: '#22c55e',
  },
  restaurant: {
    tint: 'rgba(60,25,0,0.38)',
    particles: 'rgba(230,140,40,0.6)',
    accent: '#e67e22', accentLight: '#f39c12',
    badgeBg: 'rgba(60,25,0,0.7)', badgeColor: '#fca84e',
    btnGrad: 'linear-gradient(135deg,#4a2000,#9a5000)',
    statColor: '#f39c12',
  },
  artisan: {
    tint: 'rgba(0,40,35,0.38)',
    particles: 'rgba(26,188,156,0.5)',
    accent: '#16a085', accentLight: '#1abc9c',
    badgeBg: 'rgba(0,30,25,0.7)', badgeColor: '#1de9b6',
    btnGrad: 'linear-gradient(135deg,#003d30,#16a085)',
    statColor: '#1abc9c',
  },
};

// ─── LIEUX PATRIMONIAUX ──────────────────────────────────────
const PLACES = [
  {
    id: 1,
    cat: 'monument',
    name: "Site archéologique de Glanum",
    page: "glanum.html",
    desc: "Cité gallo-romaine fondée au VIe siècle av. J.-C. autour d'une source sacrée. L'un des sites antiques les mieux préservés de Provence — temples, forum, thermes et maisons à péristyle.",
    addr: "Route des Baux-de-Provence, 13210 Saint-Rémy-de-Provence",
    lat: 43.7758, lng: 4.8311,
    era: "VIe siècle av. J.-C.",
    siecle: "VIe av. J.-C.",
    anecdote: "Saviez-vous ? Glanum dort sous terre depuis 1700 ans — détruite par les invasions barbares vers 260, ses habitants ont fui à un kilomètre au nord pour fonder Saint-Rémy. Il a fallu attendre 1921 pour que les fouilles redonnent vie à la cité oubliée.",
    histoire: "Fondée par les Salyens, peuple celto-ligure, autour d'une source sacrée vouée au dieu guérisseur Glan, la cité connut trois civilisations : gauloise, hellénistique puis romaine. Conquise par César, elle devint Glanum à l'époque impériale et se dota de temples, d'un forum et de thermes. Détruite vers 260, elle fut redécouverte en 1921 par Pierre de Brun.",
    timeline: [
      { year: "VIe s. av.", text: "Fondation gauloise par les Salyens" },
      { year: "Ier s. av.", text: "Conquête romaine — devient Glanum" },
      { year: "260", text: "Destruction par les invasions barbares" },
      { year: "1921", text: "Premières fouilles de Pierre de Brun" },
      { year: "1937", text: "Classement Monument Historique" },
    ],
    bg: ASSETS_PREFIX + "poi_001.jpg",
  },
  {
    id: 2,
    cat: 'religieux',
    name: "Monastère Saint-Paul-de-Mausole",
    page: "saint-paul-de-mausole.html",
    desc: "Chef-d'œuvre de l'art roman provençal du XIe siècle où Vincent van Gogh fut interné en 1889-1890. Il y peignit 143 toiles dont La Nuit étoilée et Les Iris.",
    addr: "Chemin Saint-Paul, 13210 Saint-Rémy-de-Provence",
    lat: 43.7779, lng: 4.8336,
    era: "XIe siècle",
    siecle: "XIe",
    anecdote: "Van Gogh arriva ici de son plein gré le 8 mai 1889, après l'épisode de l'oreille coupée. En 53 semaines d'internement volontaire, il peignit 143 huiles et plus de 100 dessins — la période la plus prolifique de sa vie. Sa chambre est aujourd'hui reconstituée, fenêtre donnant sur les champs qui inspirèrent La Nuit étoilée.",
    histoire: "Bâti au XIe siècle près de la source sacrée de Glanum, le monastère est un joyau de l'art roman provençal. Son cloître aux chapiteaux sculptés et son clocher carré à toit pyramidal sont classés Monument Historique depuis 1883. Devenu maison de santé en 1807, il accueille encore aujourd'hui une clinique psychiatrique — la plus ancienne de France en activité continue.",
    timeline: [
      { year: "XIe s.", text: "Construction du prieuré roman" },
      { year: "1140", text: "Édification des galeries nord et est du cloître" },
      { year: "1807", text: "Transformation en asile par le Dr Mercurin" },
      { year: "1889", text: "Internement de Vincent van Gogh" },
      { year: "1883", text: "Classement Monument Historique" },
    ],
    bg: ASSETS_PREFIX + "poi_002.jpg",
  },
  {
    id: 3,
    cat: 'monument',
    name: "Les Antiques — Mausolée & Arc de triomphe",
    page: "les-antiques.html",
    desc: "Deux monuments romains parmi les mieux conservés au monde, posés seuls sur un parvis désert. Le Mausolée des Jules et l'Arc marquent l'entrée de l'antique Glanum.",
    addr: "Avenue Vincent Van Gogh, 13210 Saint-Rémy-de-Provence",
    lat: 43.7771, lng: 4.8316,
    era: "Ier siècle av. J.-C.",
    siecle: "Ier av. J.-C.",
    anecdote: "Le Mausolée des Jules n'est pas un tombeau : c'est un cénotaphe, monument funéraire vide, érigé entre -30 et -20 av. J.-C. à la mémoire d'une famille gauloise ayant obtenu la citoyenneté romaine. Sa tholos sommitale, ce petit temple rond à colonnes, est unique au monde.",
    histoire: "Élevés à l'entrée de la cité de Glanum, ces deux monuments saluaient les voyageurs venus du nord. L'Arc de triomphe, construit sous Auguste (vers 20 ap. J.-C.), célèbre la conquête des Gaules par César — ses bas-reliefs montrent prisonniers et trophées. Le Mausolée voisin, plus ancien, est l'un des plus beaux exemples d'architecture funéraire romaine connus.",
    timeline: [
      { year: "-30/-20", text: "Construction du Mausolée des Jules" },
      { year: "20 ap. J.-C.", text: "Édification de l'Arc de triomphe" },
      { year: "XVIIIe", text: "Restauration de la toiture en lauzes" },
      { year: "1840", text: "Classement Monument Historique" },
    ],
    bg: ASSETS_PREFIX + "poi_003.jpg",
  },
  {
    id: 4,
    cat: 'culturel',
    name: "Maison natale de Nostradamus",
    desc: "Maison du XVe siècle où naquit Michel de Nostredame le 14 décembre 1503. L'apothicaire devenu astrologue rédigea ici ses premières confitures avant ses prophéties.",
    addr: "6 rue Hoche, 13210 Saint-Rémy-de-Provence",
    lat: 43.7892, lng: 4.8328,
    era: "XVe siècle",
    siecle: "XVe",
    anecdote: "Avant d'écrire ses fameuses Centuries, Nostradamus publia en 1555 le tout premier traité de confitures de la langue française — le Traité des fardemens et confitures. Saint-Rémy reste aujourd'hui un terroir de confiseries artisanales : calissons, nougats, pâtes d'amande perpétuent cet héritage gourmand.",
    histoire: "Michel de Nostredame naquit ici dans une famille de juifs convertis. Médecin formé à Montpellier, il pratiqua la médecine durant les épidémies de peste avant de se tourner vers l'astrologie. Ses Prophéties (1555) — 942 quatrains regroupés en Centuries — l'ont rendu mondialement célèbre. La maison conserve aujourd'hui sa façade médiévale d'origine.",
    timeline: [
      { year: "1503", text: "Naissance de Michel de Nostredame" },
      { year: "1555", text: "Publication des Prophéties" },
      { year: "1566", text: "Mort à Salon-de-Provence" },
      { year: "XXe s.", text: "Maison ouverte au public" },
    ],
    bg: null,
  },
  {
    id: 5,
    cat: 'naturel',
    name: "Lac du Peiroou",
    page: "lac-peiroou.html",
    desc: "Lac de retenue niché dans les Alpilles, entouré de pins et de calcaire blanc. Spot favori des Saint-Rémois pour la baignade, la randonnée et les couchers de soleil sur la garrigue.",
    addr: "Chemin du Peiroou, 13210 Saint-Rémy-de-Provence",
    lat: 43.7705, lng: 4.8408,
    era: "XIXe siècle",
    siecle: "XIXe",
    anecdote: "Les habitants l'appellent simplement 'le Peiroou' — du provençal 'peiròu' qui signifie marmite, en référence à sa forme creusée dans la roche. Aucune indication touristique ne mène ici. C'est pourtant LE spot caché des Saint-Rémois pour échapper à la foule de Glanum en été.",
    histoire: "Construit au XIXe siècle pour alimenter la ville en eau, ce barrage forme aujourd'hui un lac de 4 hectares cerné par la garrigue. Classé espace naturel sensible, il abrite une faune remarquable — couleuvres de Montpellier, aigles de Bonelli, chevreuils. Les sentiers qui le traversent rejoignent le GR6 et offrent l'une des plus belles vues sur la chaîne des Alpilles.",
    timeline: [
      { year: "1854", text: "Construction du barrage" },
      { year: "1965", text: "Classement Site Inscrit des Alpilles" },
      { year: "2007", text: "Création du Parc naturel régional" },
      { year: "2020s", text: "Aménagement des sentiers de randonnée" },
    ],
    bg: ASSETS_PREFIX + "poi_004.jpg",
  },
  {
    id: 302,
    name: "Le Trésor caché de l'Hôtel de Sade",
    anecdote: "2000 ans sous une façade",
    desc: "Derrière la façade Renaissance se cache un concentré de 2000 ans d'histoire : thermes antiques, tour médiévale, deux églises et chapelle des Pénitents Noirs superposés.",
    lat: 43.7895, lng: 4.8321,
    bg: ASSETS_PREFIX + "poi_005.jpg",
    page: "hotel-de-sade.html",
  },
];

// ─── COMMERCES ───────────────────────────────────────────────

// ─── INSOLITES ────────────────────────────────────────────────
const INSOLITES = [
  {
    id: 301,
    name: "La Source Guérisseuse de Glan",
    anecdote: "Le secret oublié de Saint-Rémy",
    desc: "Avant les Romains, avant les Grecs, les Salyens y venaient soigner leurs maux. La source sacrée coule encore aujourd'hui, à 50 mètres sous le forum de Glanum.",
    lat: 43.7758, lng: 4.8311,
    bg: ASSETS_PREFIX + "poi_006.jpg",
    page: "source-glan.html",
  },
  {
    id: 302,
    name: "La Chambre de Van Gogh",
    anecdote: "Reconstituée à l'identique",
    desc: "Chambre n°5 du monastère Saint-Paul. C'est en regardant par cette fenêtre, une nuit de juin 1889, que Vincent peignit La Nuit étoilée — le tableau le plus reproduit au monde.",
    lat: 43.7779, lng: 4.8336,
    bg: ASSETS_PREFIX + "poi_007.jpg",
    page: "chambre-van-gogh.html",
  },
];

const COMMERCES = [
  {
    id: 153,
    cat: 'artisan',
    ville: 'saint-remy',
    name: "Confiserie Lilamand",
    desc: "Confiseur depuis 1866 — calissons, fruits confits, pâtes d'amande et nougats. La maison la plus ancienne de Saint-Rémy, gardienne d'un savoir-faire hérité de Nostradamus.",
    addr: "5 avenue Albert Schweitzer, 13210 Saint-Rémy-de-Provence",
    lat: 43.7884, lng: 4.8284,
    horaires: "Lun – Sam · 9h00 – 19h00",
    tel: "04 90 92 11 08",
    note: "4.8",
    bg: ASSETS_PREFIX + "lilamand.jpg",
    page: "lilamand.html",
  },
  {
    id: 152,
    cat: 'restaurant',
    ville: 'saint-remy',
    name: "Le Bistrot Découverte",
    desc: "Bistrot provençal réputé tenu par Claude et Dana Douard. Cuisine du marché, cave d'exception et terrasse à l'ombre des platanes. L'adresse incontournable des Saint-Rémois.",
    addr: "19 boulevard Victor Hugo, 13210 Saint-Rémy-de-Provence",
    lat: 43.7898, lng: 4.8312,
    horaires: "Mar – Sam · 12h – 14h · 19h – 22h",
    tel: "04 90 92 34 49",
    note: "4.6",
    bg: ASSETS_PREFIX + "bistrot-decouverte.jpg",
    page: "bistrot-decouverte.html",
  },
  {
    id: 151,
    cat: 'restaurant',
    ville: 'saint-remy',
    name: "L'Aile ou la Cuisse",
    desc: "Cuisine provençale créative dans une cour intérieure du centre ancien. Produits du marché du mercredi, vins des Alpilles, ambiance conviviale au cœur du vieux Saint-Rémy.",
    addr: "5 rue de la Commune, 13210 Saint-Rémy-de-Provence",
    lat: 43.7902, lng: 4.8319,
    horaires: "12h – 14h · 19h – 22h30",
    note: "4.5",
    bg: ASSETS_PREFIX + "poi_008.jpg",
    page: "aile-ou-cuisse.html",
  },
  {
    id: 101,
    cat: 'restaurant',
    name: "La Maison Drouot",
    desc: "Cuisine gastronomique aux saveurs des Alpilles — agneau de pays, truffe noire du Vaucluse, huile d'olive AOP, vins des Baux-de-Provence.",
    addr: "Saint-Rémy-de-Provence",
    lat: 43.7891, lng: 4.8325,
    horaires: "Mer-Dim 12h-14h · 19h-22h",
    tel: "04 90 XX XX XX",
  },
  {
    id: 102,
    cat: 'artisan',
    name: "Moulin du Calanquet",
    desc: "Moulin à huile familial — huiles d'olive AOP Vallée des Baux, tapenades et produits du terroir provençal. Visite et dégustation sur place.",
    addr: "Saint-Rémy-de-Provence",
    lat: 43.7821, lng: 4.8189,
    horaires: "Lun-Sam 9h-19h",
    tel: "04 32 60 09 50",
  },
  {
    id: 103,
    cat: 'artisan',
    name: "Marché du Mercredi",
    desc: "Le grand marché provençal — plus de 150 exposants toute l'année, jusqu'à 300 en haute saison. L'un des plus vivants de Provence.",
    addr: "Place de la République, Saint-Rémy-de-Provence",
    lat: 43.7895, lng: 4.8311,
    horaires: "Mercredi 8h-13h",
    tel: null,
  },
  {
    id: 104,
    cat: 'artisan',
    name: "Marché du Samedi",
    desc: "Petit marché 100% producteurs locaux — fromages de chèvre des Alpilles, miels, légumes bio, fruits de saison. Une quinzaine d'étals exclusivement alimentaires.",
    addr: "Avenue de la Résistance, Saint-Rémy-de-Provence",
    lat: 43.7906, lng: 4.8298,
    horaires: "Samedi 8h-13h",
    tel: null,
  },
];

// ─── ÉVÉNEMENTS ──────────────────────────────────────────────
const EVENEMENTS = [
  {
    id: 201,
    cat: 'evenement',
    ville: 'saint-remy',
    name: "Marché Nocturne des Créateurs",
    desc: "Artisans, créateurs et producteurs s'installent en centre-ville à la fraîcheur du soir — fanfares, groupes folkloriques et ambiance estivale jusque tard.",
    addr: "Centre-ville, 13210 Saint-Rémy-de-Provence",
    lat: 43.7898, lng: 4.8315,
    date: "Mardis soirs · juillet à mi-septembre",
    horaires: "19h – 23h30",
    note: "4.8",
    bg: ASSETS_PREFIX + "poi_009.jpg",
    page: "marche-nocturne.html",
  },

  {
    id: 202,
    cat: 'fete',
    name: "Fête de la Transhumance",
    desc: "Plus de 4 000 moutons, chèvres et ânes traversent le centre-ville guidés par leurs bergers en costume — l'une des fêtes les plus emblématiques des Alpilles.",
    lat: 43.7895, lng: 4.8311,
    date: "Lundi de Pentecôte",
  },
  {
    id: 203,
    cat: 'culturel',
    name: "Festival Organa",
    desc: "Les plus grands organistes internationaux se produisent à la Collégiale Saint-Martin — concerts gratuits tous les samedis de juillet à septembre.",
    lat: 43.7896, lng: 4.8316,
    date: "Juillet – Septembre",
  },
  {
    id: 204,
    cat: 'fete',
    name: "Féria de Saint-Rémy",
    desc: "Quatre jours de manifestations taurines provençales autour du 15 août — courses camarguaises, abrivado, bodegas et défilé de la Carreto Ramado.",
    lat: 43.7899, lng: 4.8307,
    date: "Mi-août",
  },
];
